/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/server.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface Post {
    id: bigint;
    title: string;
    body: string;
    author: string;
    summary: string;
}
export type GetPostResult = {
    __kind__: "Ok";
    Ok: Post;
} | {
    __kind__: "Err";
    Err: string;
};
export type HeaderField = [string, string];
export interface HttpRequest {
    url: string;
    method: string;
    body: Uint8Array;
    headers: Array<HeaderField>;
    certificate_version?: number;
}
export interface HttpResponse {
    body: Uint8Array;
    headers: Array<HeaderField>;
    status_code: number;
}
export interface serverInterface {
    get_post(arg0: bigint): Promise<GetPostResult>;
    http_request(request: HttpRequest): Promise<HttpResponse>;
    http_request_update(request: HttpRequest): Promise<HttpResponse>;
    list_posts(): Promise<Array<Post>>;
}
import type { GetPostResult as _GetPostResult, HeaderField as _HeaderField, HttpRequest as _HttpRequest, Post as _Post } from "./declarations/server.did.d.ts";
export class Server implements serverInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async get_post(arg0: bigint): Promise<GetPostResult> {
        const result = await this.actor.get_post(arg0);
        return from_candid_GetPostResult_n1(result);
    }
    async http_request(arg0: HttpRequest): Promise<HttpResponse> {
        const result = await this.actor.http_request(to_candid_HttpRequest_n3(arg0));
        return result;
    }
    async http_request_update(arg0: HttpRequest): Promise<HttpResponse> {
        const result = await this.actor.http_request_update(to_candid_HttpRequest_n3(arg0));
        return result;
    }
    async list_posts(): Promise<Array<Post>> {
        const result = await this.actor.list_posts();
        return result;
    }
}
function from_candid_GetPostResult_n1(value: _GetPostResult): GetPostResult {
    return from_candid_variant_n2(value);
}
function from_candid_variant_n2(value: {
    Ok: _Post;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Post;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function to_candid_HttpRequest_n3(value: HttpRequest): _HttpRequest {
    return to_candid_record_n4(value);
}
function to_candid_record_n4(value: {
    url: string;
    method: string;
    body: Uint8Array;
    headers: Array<HeaderField>;
    certificate_version?: number;
}): {
    url: string;
    method: string;
    body: Uint8Array;
    headers: Array<_HeaderField>;
    certificate_version: [] | [number];
} {
    return {
        url: value.url,
        method: value.method,
        body: value.body,
        headers: value.headers,
        certificate_version: value.certificate_version ? candid_some(value.certificate_version) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Server {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Server(actor);
}
