use ic_cdk::{init, post_upgrade, query, update};
use ic_http_certification::{HttpRequest, HttpResponse};
use include_dir::{include_dir, Dir};

pub mod data;
pub mod routes;

// Auto-generated by build.rs via ic_asset_router::build::generate_routes().
// The route tree is generated into OUT_DIR and pulled in via include!.
mod route_tree {
    include!(concat!(env!("OUT_DIR"), "/__route_tree.rs"));
}

static ASSET_DIR: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/static");

// ---------------------------------------------------------------------------
// Canister lifecycle
// ---------------------------------------------------------------------------

fn setup() {
    ic_asset_router::set_asset_config(ic_asset_router::AssetConfig {
        security_headers: ic_asset_router::SecurityHeaders::permissive(),
        cache_control: ic_asset_router::CacheControl {
            static_assets: "public, max-age=31536000, immutable".into(),
            dynamic_assets: "public, no-cache, no-store".into(),
        },
        cache_config: ic_asset_router::CacheConfig::default(),
        custom_headers: vec![],
    });
    ic_asset_router::assets::certify_all_assets(&ASSET_DIR);
}

#[init]
fn init() {
    setup();
}

#[post_upgrade]
fn post_upgrade() {
    setup();
}

// ---------------------------------------------------------------------------
// HTTP interface
// ---------------------------------------------------------------------------

#[query]
fn http_request(req: HttpRequest) -> HttpResponse<'static> {
    route_tree::ROUTES.with(|routes| {
        ic_asset_router::http_request(
            req,
            routes,
            ic_asset_router::HttpRequestOptions { certify: true },
        )
    })
}

#[update]
fn http_request_update(req: HttpRequest) -> HttpResponse<'static> {
    route_tree::ROUTES.with(|routes| ic_asset_router::http_request_update(req, routes))
}
